blueprint:
  name: Humidity-Controlled Fan with Manual Override
  description: >
    Automate a bathroom fan to turn on/off based on humidity levels with optional manual override and configurable timer. Supports optional input_boolean and input_number helpers for user control from a dashboard.
  domain: automation
  input:
    fan_switch:
      name: Fan Switch
      description: The fan switch entity.
      selector:
        entity:
          domain: switch
    bathroom_humidity:
      name: Bathroom Humidity Sensor
      description: The humidity sensor in the bathroom.
      selector:
        entity:
          domain: sensor
          device_class: humidity
    indoor_humidity:
      name: Indoor Humidity Sensor
      description: The main house humidity sensor to compare against.
      selector:
        entity:
          domain: sensor
          device_class: humidity
    manual_override_flag:
      name: Manual Override Flag (Optional)
      description: Input boolean to track manual override state (optional).
      default:
      selector:
        entity:
          filter:
            domain: input_boolean
    override_duration_helper:
      name: Override Duration Helper (Optional)
      description: Input number to allow user-adjustable override duration (optional).
      default:
      selector:
        entity:
          filter:
            domain: input_number
    humidity_on_threshold:
      name: Humidity On Threshold
      description: Humidity percentage that triggers the fan ON.
      default: 65
      selector:
        number:
          min: 50
          max: 90
          unit_of_measurement: "%"
          step: 1
    humidity_off_threshold:
      name: Humidity Off Threshold
      description: Humidity percentage that triggers the fan OFF.
      default: 62
      selector:
        number:
          min: 40
          max: 80
          unit_of_measurement: "%"
          step: 1
    humidity_delta:
      name: Humidity Delta
      description: Difference between bathroom and house humidity to consider for triggering.
      default: 5
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"
          step: 1
    manual_override_duration:
      name: Manual Override Duration (minutes)
      description: Default time to keep fan running when turned on manually.
      default: 20
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: minutes
          step: 1

trigger:
  - platform: numeric_state
    entity_id: !input bathroom_humidity
    above: !input humidity_on_threshold
    id: humidity_high
  - platform: numeric_state
    entity_id: !input bathroom_humidity
    below: !input humidity_off_threshold
    id: humidity_low
  - platform: state
    entity_id: !input fan_switch
    to: "on"
    id: manual_on

variables:
  fan_switch: !input fan_switch
  bathroom_humidity: !input bathroom_humidity
  indoor_humidity: !input indoor_humidity
  humidity_on_threshold: !input humidity_on_threshold
  humidity_off_threshold: !input humidity_off_threshold
  humidity_delta: !input humidity_delta
  manual_override_flag: !input manual_override_flag
  override_duration_helper: !input override_duration_helper
  manual_override_duration: !input manual_override_duration

action:
  - choose:
      # 💨 Turn fan on due to humidity
      - conditions:
          - condition: trigger
            id: humidity_high
          - condition: template
            value_template: >
              {{ states(bathroom_humidity)|float - states(indoor_humidity)|float > humidity_delta }}
          - condition: template
            value_template: >
              {{ manual_override_flag is none or is_state(manual_override_flag, 'off') }}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ fan_switch }}"

      # 🌬 Manual turn on detected
      - conditions:
          - condition: trigger
            id: manual_on
          - condition: template
            value_template: >
              {{ manual_override_flag is none or is_state(manual_override_flag, 'off') }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ manual_override_flag != none }}"
                sequence:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: "{{ manual_override_flag }}"
          - delay:
              minutes: >
                {{ states(override_duration_helper) | float if override_duration_helper != none else manual_override_duration }}
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ manual_override_flag != none }}"
                sequence:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: "{{ manual_override_flag }}"
          # 🚦 Check humidity before turning fan off
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ states(bathroom_humidity)|float < humidity_on_threshold }}
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: "{{ fan_switch }}"

      # 💡 Turn fan off if humidity dropped & no manual override
      - conditions:
          - condition: trigger
            id: humidity_low
          - condition: template
            value_template: >
              {{ manual_override_flag is none or is_state(manual_override_flag, 'off') }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ fan_switch }}"

mode: restart
