blueprint:
  name: Moisture Sensor Notifications
  description: >
    Send notifications when moisture sensors detect moisture.
    Supports manual sensor selection with efficient state-based triggers.
  domain: automation
  author: billchurch
  source_url: https://github.com/billchurch/ha-blueprints
  input:
    moisture_sensors:
      name: Moisture Sensors
      description: Select moisture sensors to monitor
      selector:
        entity:
          filter:
            device_class: moisture
          multiple: true
    notify_devices:
      name: Notification Devices
      description: Mobile devices to receive notifications
      selector:
        device:
          filter:
            integration: mobile_app
          multiple: true
    notification_title:
      name: Notification Title
      description: Title for moisture detection notifications
      default: "Moisture Detected!"
      selector:
        text:
    notification_message:
      name: Notification Message
      description: >
        Message template. Available variables:
        {{ trigger.to_state.name }} - Sensor name
        {{ trigger.entity_id }} - Sensor entity ID
        {{ trigger.to_state.state }} - Current state
        {{ area_name(trigger.entity_id) }} - Sensor area
      default: "Moisture detected by {{ trigger.to_state.name }} in {{ area_name(trigger.entity_id) | default('Unknown Location', true) }}"
      selector:
        text:
          multiline: true
    moisture_threshold:
      name: Moisture Threshold (%)
      description: >
        Trigger when sensor value exceeds this threshold.
        Set to 0 to trigger on any 'on', 'wet', or 'moisture' state.
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
    enable_actions:
      name: Enable Action Buttons
      description: Add Acknowledge and View buttons to notifications
      default: false
      selector:
        boolean:
    repeat_enabled:
      name: Repeat Notifications
      description: Send notifications repeatedly while moisture is detected
      default: false
      selector:
        boolean:
    repeat_interval:
      name: Repeat Interval
      description: Minutes between repeated notifications
      default: 30
      selector:
        number:
          min: 5
          max: 1440
          unit_of_measurement: "min"
          mode: slider

trigger:
  - platform: state
    entity_id: !input moisture_sensors
    
condition:
  - condition: template
    value_template: >
      {% set new_state = trigger.to_state.state %}
      {% set old_state = trigger.from_state.state if trigger.from_state else 'unknown' %}
      {% set threshold = moisture_threshold | float(0) %}
      
      {# State must have changed #}
      {% if new_state == old_state %}
        {{ false }}
      {# Check for moisture detection #}
      {% elif new_state in ['on', 'wet', 'moisture'] %}
        {{ true }}
      {# Check numeric threshold if set #}
      {% elif threshold > 0 and new_state not in ['off', 'dry', 'unavailable', 'unknown'] %}
        {{ new_state | float(0) > threshold }}
      {% else %}
        {{ false }}
      {% endif %}

variables:
  notify_devices: !input notify_devices
  notification_title: !input notification_title
  notification_message: !input notification_message
  moisture_threshold: !input moisture_threshold
  enable_actions: !input enable_actions
  repeat_enabled: !input repeat_enabled
  repeat_interval: !input repeat_interval

action:
  - variables:
      notification_data:
        tag: "moisture_{{ trigger.entity_id | replace('.', '_') }}"
        group: "moisture_alerts"
        importance: high
        channel: moisture_alerts
        ttl: 0
        priority: high
        actions: >
          {% if enable_actions %}
            [{
              "action": "ACK_{{ trigger.entity_id | replace('.', '_') | upper }}",
              "title": "Acknowledge"
            },
            {
              "action": "VIEW_{{ trigger.entity_id | replace('.', '_') | upper }}",
              "title": "View Sensor",
              "uri": "/lovelace/{{ area_name(trigger.entity_id) | lower | replace(' ', '-') | default('home', true) }}"
            }]
          {% else %}
            []
          {% endif %}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ repeat_enabled }}"
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: "{{ trigger.entity_id }}"
                  state: "{{ trigger.to_state.state }}"
              sequence:
                - repeat:
                    for_each: "{{ notify_devices }}"
                    sequence:
                      - service: notify.mobile_app_{{ device_attr(repeat.item, 'name') | replace(' ', '_') | replace('-', '_') | lower }}
                        data:
                          title: "{{ notification_title }}"
                          message: "{{ notification_message }}"
                          data: "{{ notification_data }}"
                - delay:
                    minutes: "{{ repeat_interval }}"
    default:
      - repeat:
          for_each: "{{ notify_devices }}"
          sequence:
            - service: notify.mobile_app_{{ device_attr(repeat.item, 'name') | replace(' ', '_') | replace('-', '_') | lower }}
              data:
                title: "{{ notification_title }}"
                message: "{{ notification_message }}"
                data: "{{ notification_data }}"

mode: parallel
max: 10