blueprint:
  name: Pico Fan – Simple 5-Button
  description: >
    Map a Lutron Fan Pico (PJ2-3BRL-GXX-F01) to one ceiling fan
    and an optional light.
    Single presses only – no long-press or double-click logic.
  domain: automation
  author: billchurch
  source_url: https://community.home-assistant.io/t/pico-fan-simple-5-button-remote-for-lutron-caseta-haiku-or-any-fan/901507
  input:
    pico_remote:
      name: Lutron Pico
      selector:
        device:
          model: PJ2-3BRL-GXX-F01 (Pico3ButtonRaiseLower)
    fan_entity:
      name: Fan
      selector:
        entity:
          domain: fan
    light_entity:
      name: Light (optional)
      default: []
      selector:
        entity:
          domain: light
          multiple: false

trigger:
  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'on'
    id: 'on'

  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: raise
    id: 'up'

  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: stop
    id: 'middle'

  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: lower
    id: 'down'

  - platform: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'off'
    id: 'off'

action:
  - choose:
    - conditions:
        - condition: trigger
          id: 'on'
      sequence:
        - service: fan.turn_on
          target:
            entity_id: !input fan_entity

    - conditions:
        - condition: trigger
          id: 'up'
      sequence:
        - service: fan.increase_speed
          target:
            entity_id: !input fan_entity

    - conditions:
        - condition: trigger
          id: 'middle'
      sequence:
        - service: >-
            {{ 'light.toggle' if !input light_entity else 'fan.toggle' }}
          target:
            entity_id: >-
              {{ !input light_entity if !input light_entity
                 else !input fan_entity }}

    - conditions:
        - condition: trigger
          id: 'down'
      sequence:
        - service: fan.decrease_speed
          target:
            entity_id: !input fan_entity

    - conditions:
        - condition: trigger
          id: 'off'
      sequence:
        - service: fan.turn_off
          target:
            entity_id: !input fan_entity

mode: single
